// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: account/v2/account.proto

package accountv2

import (
	v11 "github.com/galadeat/bank-sim/api/proto/common/v1"
	v1 "github.com/galadeat/bank-sim/api/proto/user/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner         *v1.UserInfo           `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Balance       *v11.Money             `protobuf:"bytes,3,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountInfo) Reset() {
	*x = AccountInfo{}
	mi := &file_account_v2_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfo) ProtoMessage() {}

func (x *AccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfo.ProtoReflect.Descriptor instead.
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return file_account_v2_account_proto_rawDescGZIP(), []int{0}
}

func (x *AccountInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccountInfo) GetOwner() *v1.UserInfo {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *AccountInfo) GetBalance() *v11.Money {
	if x != nil {
		return x.Balance
	}
	return nil
}

type GetAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *AccountInfo           `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountResponse) Reset() {
	*x = GetAccountResponse{}
	mi := &file_account_v2_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse) ProtoMessage() {}

func (x *GetAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse.ProtoReflect.Descriptor instead.
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return file_account_v2_account_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccountResponse) GetAccount() *AccountInfo {
	if x != nil {
		return x.Account
	}
	return nil
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_account_v2_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_account_v2_account_proto_rawDescGZIP(), []int{2}
}

func (x *GetAccountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateAccountRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	InitialBalance *v11.Money             `protobuf:"bytes,2,opt,name=initial_balance,json=initialBalance,proto3" json:"initial_balance,omitempty"`
	RequestId      string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_account_v2_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_account_v2_account_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAccountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAccountRequest) GetInitialBalance() *v11.Money {
	if x != nil {
		return x.InitialBalance
	}
	return nil
}

func (x *CreateAccountRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *AccountInfo           `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_account_v2_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_account_v2_account_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAccountResponse) GetAccount() *AccountInfo {
	if x != nil {
		return x.Account
	}
	return nil
}

type ListAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsRequest) Reset() {
	*x = ListAccountsRequest{}
	mi := &file_account_v2_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsRequest) ProtoMessage() {}

func (x *ListAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsRequest.ProtoReflect.Descriptor instead.
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return file_account_v2_account_proto_rawDescGZIP(), []int{5}
}

func (x *ListAccountsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*AccountInfo         `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsResponse) Reset() {
	*x = ListAccountsResponse{}
	mi := &file_account_v2_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsResponse) ProtoMessage() {}

func (x *ListAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsResponse.ProtoReflect.Descriptor instead.
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return file_account_v2_account_proto_rawDescGZIP(), []int{6}
}

func (x *ListAccountsResponse) GetAccounts() []*AccountInfo {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type DeleteAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountRequest) Reset() {
	*x = DeleteAccountRequest{}
	mi := &file_account_v2_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountRequest) ProtoMessage() {}

func (x *DeleteAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return file_account_v2_account_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type DeleteAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountResponse) Reset() {
	*x = DeleteAccountResponse{}
	mi := &file_account_v2_account_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountResponse) ProtoMessage() {}

func (x *DeleteAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_account_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountResponse.ProtoReflect.Descriptor instead.
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return file_account_v2_account_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteAccountResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type DepositRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount        *v11.Money             `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositRequest) Reset() {
	*x = DepositRequest{}
	mi := &file_account_v2_account_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositRequest) ProtoMessage() {}

func (x *DepositRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_account_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositRequest.ProtoReflect.Descriptor instead.
func (*DepositRequest) Descriptor() ([]byte, []int) {
	return file_account_v2_account_proto_rawDescGZIP(), []int{9}
}

func (x *DepositRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *DepositRequest) GetAmount() *v11.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *DepositRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type DepositResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *AccountInfo           `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositResponse) Reset() {
	*x = DepositResponse{}
	mi := &file_account_v2_account_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositResponse) ProtoMessage() {}

func (x *DepositResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_account_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositResponse.ProtoReflect.Descriptor instead.
func (*DepositResponse) Descriptor() ([]byte, []int) {
	return file_account_v2_account_proto_rawDescGZIP(), []int{10}
}

func (x *DepositResponse) GetAccount() *AccountInfo {
	if x != nil {
		return x.Account
	}
	return nil
}

type WithdrawRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount        *v11.Money             `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawRequest) Reset() {
	*x = WithdrawRequest{}
	mi := &file_account_v2_account_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawRequest) ProtoMessage() {}

func (x *WithdrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_account_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawRequest.ProtoReflect.Descriptor instead.
func (*WithdrawRequest) Descriptor() ([]byte, []int) {
	return file_account_v2_account_proto_rawDescGZIP(), []int{11}
}

func (x *WithdrawRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *WithdrawRequest) GetAmount() *v11.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *WithdrawRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type WithdrawResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *AccountInfo           `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawResponse) Reset() {
	*x = WithdrawResponse{}
	mi := &file_account_v2_account_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawResponse) ProtoMessage() {}

func (x *WithdrawResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v2_account_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawResponse.ProtoReflect.Descriptor instead.
func (*WithdrawResponse) Descriptor() ([]byte, []int) {
	return file_account_v2_account_proto_rawDescGZIP(), []int{12}
}

func (x *WithdrawResponse) GetAccount() *AccountInfo {
	if x != nil {
		return x.Account
	}
	return nil
}

var File_account_v2_account_proto protoreflect.FileDescriptor

const file_account_v2_account_proto_rawDesc = "" +
	"\n" +
	"\x18account/v2/account.proto\x12\n" +
	"account.v2\x1a\x12user/v1/user.proto\x1a\x15common/v1/money.proto\"r\n" +
	"\vAccountInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x05owner\x18\x02 \x01(\v2\x11.user.v1.UserInfoR\x05owner\x12*\n" +
	"\abalance\x18\x03 \x01(\v2\x10.common.v1.MoneyR\abalance\"G\n" +
	"\x12GetAccountResponse\x121\n" +
	"\aaccount\x18\x01 \x01(\v2\x17.account.v2.AccountInfoR\aaccount\"#\n" +
	"\x11GetAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x89\x01\n" +
	"\x14CreateAccountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x129\n" +
	"\x0finitial_balance\x18\x02 \x01(\v2\x10.common.v1.MoneyR\x0einitialBalance\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"J\n" +
	"\x15CreateAccountResponse\x121\n" +
	"\aaccount\x18\x01 \x01(\v2\x17.account.v2.AccountInfoR\aaccount\".\n" +
	"\x13ListAccountsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"K\n" +
	"\x14ListAccountsResponse\x123\n" +
	"\baccounts\x18\x01 \x03(\v2\x17.account.v2.AccountInfoR\baccounts\"5\n" +
	"\x14DeleteAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"6\n" +
	"\x15DeleteAccountResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"x\n" +
	"\x0eDepositRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12(\n" +
	"\x06amount\x18\x02 \x01(\v2\x10.common.v1.MoneyR\x06amount\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"D\n" +
	"\x0fDepositResponse\x121\n" +
	"\aaccount\x18\x01 \x01(\v2\x17.account.v2.AccountInfoR\aaccount\"y\n" +
	"\x0fWithdrawRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12(\n" +
	"\x06amount\x18\x02 \x01(\v2\x10.common.v1.MoneyR\x06amount\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"E\n" +
	"\x10WithdrawResponse\x121\n" +
	"\aaccount\x18\x01 \x01(\v2\x17.account.v2.AccountInfoR\aaccount2\xe0\x03\n" +
	"\aAccount\x12T\n" +
	"\rCreateAccount\x12 .account.v2.CreateAccountRequest\x1a!.account.v2.CreateAccountResponse\x12K\n" +
	"\n" +
	"GetAccount\x12\x1d.account.v2.GetAccountRequest\x1a\x1e.account.v2.GetAccountResponse\x12Q\n" +
	"\fListAccounts\x12\x1f.account.v2.ListAccountsRequest\x1a .account.v2.ListAccountsResponse\x12T\n" +
	"\rDeleteAccount\x12 .account.v2.DeleteAccountRequest\x1a!.account.v2.DeleteAccountResponse\x12B\n" +
	"\aDeposit\x12\x1a.account.v2.DepositRequest\x1a\x1b.account.v2.DepositResponse\x12E\n" +
	"\bWithdraw\x12\x1b.account.v2.WithdrawRequest\x1a\x1c.account.v2.WithdrawResponseB=Z;github.com/galadeat/bank-sim/api/proto/account/v2;accountv2b\x06proto3"

var (
	file_account_v2_account_proto_rawDescOnce sync.Once
	file_account_v2_account_proto_rawDescData []byte
)

func file_account_v2_account_proto_rawDescGZIP() []byte {
	file_account_v2_account_proto_rawDescOnce.Do(func() {
		file_account_v2_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_v2_account_proto_rawDesc), len(file_account_v2_account_proto_rawDesc)))
	})
	return file_account_v2_account_proto_rawDescData
}

var file_account_v2_account_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_account_v2_account_proto_goTypes = []any{
	(*AccountInfo)(nil),           // 0: account.v2.AccountInfo
	(*GetAccountResponse)(nil),    // 1: account.v2.GetAccountResponse
	(*GetAccountRequest)(nil),     // 2: account.v2.GetAccountRequest
	(*CreateAccountRequest)(nil),  // 3: account.v2.CreateAccountRequest
	(*CreateAccountResponse)(nil), // 4: account.v2.CreateAccountResponse
	(*ListAccountsRequest)(nil),   // 5: account.v2.ListAccountsRequest
	(*ListAccountsResponse)(nil),  // 6: account.v2.ListAccountsResponse
	(*DeleteAccountRequest)(nil),  // 7: account.v2.DeleteAccountRequest
	(*DeleteAccountResponse)(nil), // 8: account.v2.DeleteAccountResponse
	(*DepositRequest)(nil),        // 9: account.v2.DepositRequest
	(*DepositResponse)(nil),       // 10: account.v2.DepositResponse
	(*WithdrawRequest)(nil),       // 11: account.v2.WithdrawRequest
	(*WithdrawResponse)(nil),      // 12: account.v2.WithdrawResponse
	(*v1.UserInfo)(nil),           // 13: user.v1.UserInfo
	(*v11.Money)(nil),             // 14: common.v1.Money
}
var file_account_v2_account_proto_depIdxs = []int32{
	13, // 0: account.v2.AccountInfo.owner:type_name -> user.v1.UserInfo
	14, // 1: account.v2.AccountInfo.balance:type_name -> common.v1.Money
	0,  // 2: account.v2.GetAccountResponse.account:type_name -> account.v2.AccountInfo
	14, // 3: account.v2.CreateAccountRequest.initial_balance:type_name -> common.v1.Money
	0,  // 4: account.v2.CreateAccountResponse.account:type_name -> account.v2.AccountInfo
	0,  // 5: account.v2.ListAccountsResponse.accounts:type_name -> account.v2.AccountInfo
	14, // 6: account.v2.DepositRequest.amount:type_name -> common.v1.Money
	0,  // 7: account.v2.DepositResponse.account:type_name -> account.v2.AccountInfo
	14, // 8: account.v2.WithdrawRequest.amount:type_name -> common.v1.Money
	0,  // 9: account.v2.WithdrawResponse.account:type_name -> account.v2.AccountInfo
	3,  // 10: account.v2.Account.CreateAccount:input_type -> account.v2.CreateAccountRequest
	2,  // 11: account.v2.Account.GetAccount:input_type -> account.v2.GetAccountRequest
	5,  // 12: account.v2.Account.ListAccounts:input_type -> account.v2.ListAccountsRequest
	7,  // 13: account.v2.Account.DeleteAccount:input_type -> account.v2.DeleteAccountRequest
	9,  // 14: account.v2.Account.Deposit:input_type -> account.v2.DepositRequest
	11, // 15: account.v2.Account.Withdraw:input_type -> account.v2.WithdrawRequest
	4,  // 16: account.v2.Account.CreateAccount:output_type -> account.v2.CreateAccountResponse
	1,  // 17: account.v2.Account.GetAccount:output_type -> account.v2.GetAccountResponse
	6,  // 18: account.v2.Account.ListAccounts:output_type -> account.v2.ListAccountsResponse
	8,  // 19: account.v2.Account.DeleteAccount:output_type -> account.v2.DeleteAccountResponse
	10, // 20: account.v2.Account.Deposit:output_type -> account.v2.DepositResponse
	12, // 21: account.v2.Account.Withdraw:output_type -> account.v2.WithdrawResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_account_v2_account_proto_init() }
func file_account_v2_account_proto_init() {
	if File_account_v2_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_v2_account_proto_rawDesc), len(file_account_v2_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_v2_account_proto_goTypes,
		DependencyIndexes: file_account_v2_account_proto_depIdxs,
		MessageInfos:      file_account_v2_account_proto_msgTypes,
	}.Build()
	File_account_v2_account_proto = out.File
	file_account_v2_account_proto_goTypes = nil
	file_account_v2_account_proto_depIdxs = nil
}
