// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: reporting/v1/reporting.proto

package reportingv1

import (
	v1 "github.com/galadeat/bank-sim/api/proto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatementRequest) Reset() {
	*x = GetStatementRequest{}
	mi := &file_reporting_v1_reporting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatementRequest) ProtoMessage() {}

func (x *GetStatementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reporting_v1_reporting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatementRequest.ProtoReflect.Descriptor instead.
func (*GetStatementRequest) Descriptor() ([]byte, []int) {
	return file_reporting_v1_reporting_proto_rawDescGZIP(), []int{0}
}

func (x *GetStatementRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetStatementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*TransactionRecord   `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatementResponse) Reset() {
	*x = GetStatementResponse{}
	mi := &file_reporting_v1_reporting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatementResponse) ProtoMessage() {}

func (x *GetStatementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reporting_v1_reporting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatementResponse.ProtoReflect.Descriptor instead.
func (*GetStatementResponse) Descriptor() ([]byte, []int) {
	return file_reporting_v1_reporting_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatementResponse) GetRecords() []*TransactionRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type TransactionRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // deposit, withdraw, transfer
	Amount        *v1.Money              `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRecord) Reset() {
	*x = TransactionRecord{}
	mi := &file_reporting_v1_reporting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRecord) ProtoMessage() {}

func (x *TransactionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_reporting_v1_reporting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRecord.ProtoReflect.Descriptor instead.
func (*TransactionRecord) Descriptor() ([]byte, []int) {
	return file_reporting_v1_reporting_proto_rawDescGZIP(), []int{2}
}

func (x *TransactionRecord) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransactionRecord) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TransactionRecord) GetAmount() *v1.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *TransactionRecord) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_reporting_v1_reporting_proto protoreflect.FileDescriptor

const file_reporting_v1_reporting_proto_rawDesc = "" +
	"\n" +
	"\x1creporting/v1/reporting.proto\x12\freporting.v1\x1a\x15common/v1/money.proto\"4\n" +
	"\x13GetStatementRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"Q\n" +
	"\x14GetStatementResponse\x129\n" +
	"\arecords\x18\x01 \x03(\v2\x1f.reporting.v1.TransactionRecordR\arecords\"\x96\x01\n" +
	"\x11TransactionRecord\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12(\n" +
	"\x06amount\x18\x03 \x01(\v2\x10.common.v1.MoneyR\x06amount\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp2b\n" +
	"\tReporting\x12U\n" +
	"\fGetStatement\x12!.reporting.v1.GetStatementRequest\x1a\".reporting.v1.GetStatementResponseBAZ?github.com/galadeat/bank-sim/api/proto/reporting/v1;reportingv1b\x06proto3"

var (
	file_reporting_v1_reporting_proto_rawDescOnce sync.Once
	file_reporting_v1_reporting_proto_rawDescData []byte
)

func file_reporting_v1_reporting_proto_rawDescGZIP() []byte {
	file_reporting_v1_reporting_proto_rawDescOnce.Do(func() {
		file_reporting_v1_reporting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reporting_v1_reporting_proto_rawDesc), len(file_reporting_v1_reporting_proto_rawDesc)))
	})
	return file_reporting_v1_reporting_proto_rawDescData
}

var file_reporting_v1_reporting_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_reporting_v1_reporting_proto_goTypes = []any{
	(*GetStatementRequest)(nil),  // 0: reporting.v1.GetStatementRequest
	(*GetStatementResponse)(nil), // 1: reporting.v1.GetStatementResponse
	(*TransactionRecord)(nil),    // 2: reporting.v1.TransactionRecord
	(*v1.Money)(nil),             // 3: common.v1.Money
}
var file_reporting_v1_reporting_proto_depIdxs = []int32{
	2, // 0: reporting.v1.GetStatementResponse.records:type_name -> reporting.v1.TransactionRecord
	3, // 1: reporting.v1.TransactionRecord.amount:type_name -> common.v1.Money
	0, // 2: reporting.v1.Reporting.GetStatement:input_type -> reporting.v1.GetStatementRequest
	1, // 3: reporting.v1.Reporting.GetStatement:output_type -> reporting.v1.GetStatementResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_reporting_v1_reporting_proto_init() }
func file_reporting_v1_reporting_proto_init() {
	if File_reporting_v1_reporting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reporting_v1_reporting_proto_rawDesc), len(file_reporting_v1_reporting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reporting_v1_reporting_proto_goTypes,
		DependencyIndexes: file_reporting_v1_reporting_proto_depIdxs,
		MessageInfos:      file_reporting_v1_reporting_proto_msgTypes,
	}.Build()
	File_reporting_v1_reporting_proto = out.File
	file_reporting_v1_reporting_proto_goTypes = nil
	file_reporting_v1_reporting_proto_depIdxs = nil
}
