// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: reporting/v1/reporting.proto

package reportingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Reporting_GetStatement_FullMethodName = "/reporting.v1.Reporting/GetStatement"
)

// ReportingClient is the client API for Reporting service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReportingClient interface {
	GetStatement(ctx context.Context, in *GetStatementRequest, opts ...grpc.CallOption) (*GetStatementResponse, error)
}

type reportingClient struct {
	cc grpc.ClientConnInterface
}

func NewReportingClient(cc grpc.ClientConnInterface) ReportingClient {
	return &reportingClient{cc}
}

func (c *reportingClient) GetStatement(ctx context.Context, in *GetStatementRequest, opts ...grpc.CallOption) (*GetStatementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatementResponse)
	err := c.cc.Invoke(ctx, Reporting_GetStatement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReportingServer is the server API for Reporting service.
// All implementations must embed UnimplementedReportingServer
// for forward compatibility.
type ReportingServer interface {
	GetStatement(context.Context, *GetStatementRequest) (*GetStatementResponse, error)
	mustEmbedUnimplementedReportingServer()
}

// UnimplementedReportingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReportingServer struct{}

func (UnimplementedReportingServer) GetStatement(context.Context, *GetStatementRequest) (*GetStatementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatement not implemented")
}
func (UnimplementedReportingServer) mustEmbedUnimplementedReportingServer() {}
func (UnimplementedReportingServer) testEmbeddedByValue()                   {}

// UnsafeReportingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReportingServer will
// result in compilation errors.
type UnsafeReportingServer interface {
	mustEmbedUnimplementedReportingServer()
}

func RegisterReportingServer(s grpc.ServiceRegistrar, srv ReportingServer) {
	// If the following call pancis, it indicates UnimplementedReportingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Reporting_ServiceDesc, srv)
}

func _Reporting_GetStatement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportingServer).GetStatement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reporting_GetStatement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportingServer).GetStatement(ctx, req.(*GetStatementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Reporting_ServiceDesc is the grpc.ServiceDesc for Reporting service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Reporting_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reporting.v1.Reporting",
	HandlerType: (*ReportingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatement",
			Handler:    _Reporting_GetStatement_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reporting/v1/reporting.proto",
}
